import {
  Assessment,
  ExternalReportSummary,
  InterventionPlan,
  Learner,
  Observation,
  ProgressRecord,
  Recommendation,
} from "./types";

const now = "2026-06-16T09:00:00.000Z";

function historyEntry(
  availability: "Available" | "Not available" | "For follow-up" | "Not disclosed" | "Not authorized",
  source: "Parent/guardian report" | "Dev Ped report" | "Medical record" | "School record" | "OT report" | "ST report" | "ABA report" | "SPED report" | "Teacher observation",
  useInRecommendation: "Yes" | "No" | "Unsure" | "Restricted",
  shortSummary: string
) {
  return { availability, source, useInRecommendation, shortSummary };
}

export const prototypeAssumptionNote =
  "Prototype parameters are based on expert responses and realistic SNED/SPED practice assumptions. Final fields and rules are subject to expert follow-up validation.";

export const confidentialityNotice =
  "Confidential support documentation. Access, use, and sharing must follow learner consent, center privacy protocols, and authorized staff review.";

export const mockLearners: Learner[] = [
  {
    id: "L-001",
    code: "RA-2026-001",
    displayName: "Miguel A.",
    anonymizedId: "Learner Alpha-01",
    privacyMode: "Named Record",
    gradeLevel: "Grade 1",
    age: 7,
    gender: "Male",
    disabilityCategory: "Autism Spectrum Condition / Reading Comprehension Support",
    diagnosisStatus: "Diagnosed",
    identifiedCondition: "Autism Spectrum Disorder",
    communicationLevel: "Uses AAC/visual support",
    attentionBehaviorSupportLevel: "High",
    sensoryLearningConsiderations: ["Visual schedule support", "Noise-sensitive during long reading tasks"],
    currentReadingLevel: "Early sentence-level reading",
    readingConcerns: ["Following Instructions", "Vocabulary", "Inferential Comprehension"],
    supportNeeds: "High Support Need",
    accommodations: ["Visual schedules", "Picture-supported choices", "Extended processing time"],
    iepGoals: ["Follow 2-step reading task instructions with visual cueing", "Identify 8 target vocabulary words using picture-word matching"],
    historySummary: {
      medicalHistory: historyEntry("Available", "Dev Ped report", "Restricted", "Authorized summary notes communication-related support needs and attention considerations relevant to reading-task access."),
      developmentalHistory: historyEntry("Available", "Parent/guardian report", "Unsure", "Delayed expressive language was reported in earlier intervention history; use only as supporting context for pacing and response demands."),
      familyHistory: historyEntry("Available", "Parent/guardian report", "Yes", "Family reports the learner responds well to routines, visuals, and repeated home reading practice."),
      academicHistory: historyEntry("Available", "School record", "Yes", "Previous school-year notes describe difficulty sustaining attention during language-heavy reading tasks."),
      relatedServiceHistory: historyEntry("Available", "ST report", "Yes", "Speech therapy and SPED pull-out summaries indicate stronger participation when visual supports and short modeled responses are used."),
    },
    consentStatus: "Granted",
    dataAccessSensitivity: "Restricted",
    interventionHistory: [
      {
        id: "IH-001",
        date: "2026-05-22",
        strategy: "Picture-word preview before guided reading",
        outcome: "Answered 5 of 8 vocabulary targets with picture cues.",
        teacherReflection: "Retain visuals and reduce passage length before inferential questions.",
      },
    ],
    status: "Needs Modified Support",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "L-002",
    code: "RA-2026-002",
    displayName: "Alyssa R.",
    anonymizedId: "Learner Bravo-02",
    privacyMode: "Named Record",
    gradeLevel: "Grade 2",
    age: 8,
    gender: "Female",
    disabilityCategory: "Specific Reading / Language Support Need",
    diagnosisStatus: "For evaluation",
    identifiedCondition: "Not specified",
    communicationLevel: "Verbal",
    attentionBehaviorSupportLevel: "Moderate",
    sensoryLearningConsiderations: ["Benefits from color-coded organizers"],
    currentReadingLevel: "Short paragraph level with support",
    readingConcerns: ["Sequencing", "Main Idea"],
    supportNeeds: "Moderate Support Need",
    accommodations: ["Graphic organizers", "Chunked reading tasks", "Frequent checks for understanding"],
    iepGoals: ["Sequence 4 story events using a beginning-middle-end organizer", "State the main idea with one prompt"],
    historySummary: {
      medicalHistory: historyEntry("Not disclosed", "Parent/guardian report", "Restricted", "No formal medical diagnosis was disclosed for educational planning at this time."),
      developmentalHistory: historyEntry("For follow-up", "Parent/guardian report", "Unsure", "Parent reported an early speech delay, but no updated developmental summary has been authorized yet."),
      familyHistory: historyEntry("Available", "Parent/guardian report", "Yes", "Family provides regular home reading support and follows up on classroom recommendations."),
      academicHistory: historyEntry("Available", "School record", "Yes", "Academic assessment shows stronger literal recall than sequencing and summarization performance."),
      relatedServiceHistory: historyEntry("For follow-up", "SPED report", "Unsure", "SPED consult support is in place; updated evaluation and service notes are still pending follow-up."),
    },
    consentStatus: "Granted",
    dataAccessSensitivity: "Standard",
    interventionHistory: [
      {
        id: "IH-002",
        date: "2026-05-26",
        strategy: "Story sequencing cards and oral retell",
        outcome: "Sequenced 3 of 4 events independently after modeling.",
        teacherReflection: "Continue visual sequencing and add sentence frames for main idea.",
      },
    ],
    status: "Improving",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "L-003",
    code: "RA-2026-003",
    displayName: "Learner C-03",
    anonymizedId: "Learner C-03",
    privacyMode: "Anonymized Record",
    gradeLevel: "Grade 3",
    age: 9,
    gender: "Not disclosed",
    disabilityCategory: "Attention and Language-Related Support Need",
    diagnosisStatus: "Not disclosed",
    identifiedCondition: "Not specified",
    communicationLevel: "Limited verbal",
    attentionBehaviorSupportLevel: "Moderate",
    sensoryLearningConsiderations: ["Needs reduced visual clutter", "Responds to short tasks"],
    currentReadingLevel: "Phrase to sentence level",
    readingConcerns: ["Literal Comprehension", "Attention During Reading Task"],
    supportNeeds: "Moderate Support Need",
    accommodations: ["Reduced-distraction seating", "Highlighting", "Visual timer"],
    iepGoals: ["Answer explicit who/what questions from a short passage", "Sustain attention for one chunked reading task"],
    historySummary: {
      medicalHistory: historyEntry("Not authorized", "Medical record", "Restricted", "Medical details are restricted by privacy mode and should not be used directly in recommendations."),
      developmentalHistory: historyEntry("Not authorized", "Parent/guardian report", "Restricted", "Developmental details are restricted by privacy mode."),
      familyHistory: historyEntry("Not disclosed", "Parent/guardian report", "Restricted", "Family background details are not disclosed in this learner record."),
      academicHistory: historyEntry("Available", "Teacher observation", "Yes", "Teacher notes difficulty retaining explicit details without visual marking or reduced visual clutter."),
      relatedServiceHistory: historyEntry("Not authorized", "SPED report", "Restricted", "Related-service details are restricted and available only through authorized channels."),
    },
    consentStatus: "Limited",
    dataAccessSensitivity: "Highly restricted",
    interventionHistory: [],
    status: "Stable",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "L-004",
    code: "RA-2026-004",
    displayName: "Janelle S.",
    anonymizedId: "Learner Delta-04",
    privacyMode: "Named Record",
    gradeLevel: "Grade 4",
    age: 10,
    gender: "Female",
    disabilityCategory: "Speech/Language and Reading Comprehension Support",
    diagnosisStatus: "Diagnosed",
    identifiedCondition: "Speech/Language Difficulty",
    communicationLevel: "Verbal",
    attentionBehaviorSupportLevel: "Low",
    sensoryLearningConsiderations: ["Benefits from oral rehearsal before answering"],
    currentReadingLevel: "Paragraph level",
    readingConcerns: ["Inferential Comprehension", "Vocabulary"],
    supportNeeds: "Moderate Support Need",
    accommodations: ["Vocabulary preview", "Oral response option", "Teacher think-aloud"],
    iepGoals: ["Answer guided why/how questions using sentence frames", "Use context clues to identify unfamiliar words"],
    historySummary: {
      medicalHistory: historyEntry("Available", "Medical record", "Restricted", "Authorized summary references speech/language-related findings relevant to classroom communication support."),
      developmentalHistory: historyEntry("Not available", "Parent/guardian report", "No", "No additional developmental concerns were encoded in the current authorized summary."),
      familyHistory: historyEntry("Available", "Parent/guardian report", "Yes", "Family reports improved learner confidence during oral reading and guided discussion."),
      academicHistory: historyEntry("Available", "School record", "Yes", "Academic reading tasks indicate stronger decoding and literal recall than inferential response generation."),
      relatedServiceHistory: historyEntry("Available", "ST report", "Yes", "Speech therapy summary supports oral rehearsal and sentence starters before inferential responses."),
    },
    consentStatus: "Granted",
    dataAccessSensitivity: "Restricted",
    interventionHistory: [],
    status: "Stable",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "L-005",
    code: "RA-2026-005",
    displayName: "Paolo G.",
    anonymizedId: "Learner Echo-05",
    privacyMode: "Named Record",
    gradeLevel: "Grade 5",
    age: 11,
    gender: "Male",
    disabilityCategory: "Multiple Learning Support Needs",
    diagnosisStatus: "Diagnosed",
    identifiedCondition: "ADHD",
    communicationLevel: "Verbal",
    attentionBehaviorSupportLevel: "High",
    sensoryLearningConsiderations: ["Needs movement break between tasks", "Benefits from checklist prompts"],
    currentReadingLevel: "Short text level with prompting",
    readingConcerns: ["Attention During Reading Task", "Main Idea", "Following Instructions"],
    supportNeeds: "High Support Need",
    accommodations: ["Scheduled breaks", "Visual task checklist", "Step-by-step instructions"],
    iepGoals: ["Complete a reading task checklist with one reminder", "Identify the main idea after chunked reading"],
    historySummary: {
      medicalHistory: historyEntry("Available", "Medical record", "Restricted", "Authorized summary notes attention-related support needs that may affect reading-task stamina."),
      developmentalHistory: historyEntry("Not available", "Parent/guardian report", "No", "No new developmental summary was encoded this term."),
      familyHistory: historyEntry("Available", "Parent/guardian report", "Yes", "Parent reports better learner response to structured routines, movement breaks, and checklists."),
      academicHistory: historyEntry("Available", "School record", "Yes", "Reading accuracy is stronger than sustained task completion and main-idea explanation."),
      relatedServiceHistory: historyEntry("For follow-up", "ABA report", "Restricted", "SPED and ABA summaries were referenced in planning, but updated authorized service notes are still pending."),
    },
    consentStatus: "Pending",
    dataAccessSensitivity: "Restricted",
    interventionHistory: [],
    status: "Needs Modified Support",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "L-006",
    code: "RA-2026-006",
    displayName: "Nina V.",
    anonymizedId: "Learner Foxtrot-06",
    privacyMode: "Named Record",
    gradeLevel: "Grade 6",
    age: 12,
    gender: "Female",
    disabilityCategory: "Specific Reading Support Need",
    diagnosisStatus: "No formal diagnosis",
    identifiedCondition: "Other",
    communicationLevel: "Verbal",
    attentionBehaviorSupportLevel: "Low",
    sensoryLearningConsiderations: ["Works well with graphic summarizers"],
    currentReadingLevel: "Grade-level text with guided support",
    readingConcerns: ["Main Idea", "Inferential Comprehension"],
    supportNeeds: "Low Support Need",
    accommodations: ["Graphic organizers", "Key-detail highlighting"],
    iepGoals: ["State the main idea and two supporting details from a passage", "Make one inference using textual clues"],
    historySummary: {
      medicalHistory: historyEntry("Not available", "Medical record", "No", "No formal medical diagnosis is currently on record for this learner."),
      developmentalHistory: historyEntry("Not available", "Parent/guardian report", "No", "No developmental concerns were formally encoded in the learner record."),
      familyHistory: historyEntry("Available", "Parent/guardian report", "Yes", "Parent reports an independent home reading habit and good follow-through with reading tasks."),
      academicHistory: historyEntry("Available", "School record", "Yes", "Academic reading tasks show mild inferential difficulty despite generally independent performance."),
      relatedServiceHistory: historyEntry("Not available", "Teacher observation", "No", "No OT, ST, ABA, or SPED report summary is currently attached."),
    },
    consentStatus: "Granted",
    dataAccessSensitivity: "Standard",
    interventionHistory: [],
    status: "Improving",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockExternalReports: ExternalReportSummary[] = [
  {
    id: "ER-101",
    learnerId: "L-001",
    reportType: "Dev Ped Report",
    availability: "Available",
    reportDate: "2026-04-18",
    source: "Cradle Center Developmental Pediatrician",
    encodedBy: "Teacher Alvin",
    authorizedForUse: true,
    keyFindingsSummary: "External report notes communication and attention needs during language-heavy tasks. Reading support planning should use visuals, simplified instructions, and guided participation.",
    existingRecommendations: ["Use visual supports consistently", "Coordinate goals with speech therapy", "Keep directions short and sequenced"],
    attachmentName: "Confidential file reference pending",
    confidentialityNotice,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ER-102",
    learnerId: "L-001",
    reportType: "ST Report",
    availability: "Available",
    reportDate: "2026-05-03",
    source: "Partner Speech Therapist",
    encodedBy: "Teacher Alvin",
    authorizedForUse: true,
    keyFindingsSummary: "Learner responds better to visual choices and short modeled language. Receptive comprehension improves when unfamiliar vocabulary is previewed.",
    existingRecommendations: ["Preview target vocabulary", "Offer picture-supported response choices"],
    attachmentName: "Confidential file reference pending",
    confidentialityNotice,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ER-103",
    learnerId: "L-002",
    reportType: "Academic Assessment",
    availability: "Available",
    reportDate: "2026-05-12",
    source: "Center Academic Assessment",
    encodedBy: "Reading Teacher Maria",
    authorizedForUse: true,
    keyFindingsSummary: "Learner recalls explicit details but needs guided support for sequencing and summarizing. Main idea responses improve with organizers.",
    existingRecommendations: ["Use beginning-middle-end organizer", "Add oral retell before written summary"],
    attachmentName: "Confidential file reference pending",
    confidentialityNotice,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ER-104",
    learnerId: "L-004",
    reportType: "ST Report",
    availability: "Available",
    reportDate: "2026-04-29",
    source: "Speech Therapy Summary",
    encodedBy: "Teacher Alvin",
    authorizedForUse: true,
    keyFindingsSummary: "Expressive language support remains necessary during inferential responses, but oral rehearsal and sentence starters improve output quality.",
    existingRecommendations: ["Use oral rehearsal", "Provide sentence starters during inferential response tasks"],
    attachmentName: "Confidential file reference pending",
    confidentialityNotice,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ER-105",
    learnerId: "L-005",
    reportType: "ABA Report",
    availability: "For follow-up",
    reportDate: "2026-05-20",
    source: "Behavior Therapy Team",
    encodedBy: "Teacher Alvin",
    authorizedForUse: false,
    keyFindingsSummary: "Follow-up summary pending authorization. Current team discussion notes high need for structured prompting and regulated transitions.",
    existingRecommendations: ["Await updated authorized report", "Continue using visual task checklists"],
    attachmentName: "Confidential file reference pending",
    confidentialityNotice,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockAssessments: Assessment[] = [
  {
    id: "A-101",
    learnerId: "L-001",
    date: "2026-06-01",
    literalScore: 5,
    inferentialScore: 2,
    vocabularyScore: 3,
    sequencingScore: 4,
    mainIdeaScore: 3,
    followingInstructionsScore: 4,
    attentionDuringReadingScore: 3,
    promptingNeededScore: 8,
    responseMode: "AAC",
    accommodationsUsed: ["Visual schedules", "Picture-supported choices"],
    source: "Teacher-administered reading task",
    totalScore: 17,
    percentage: 34,
    lowestDomains: ["Inferential Comprehension", "Vocabulary", "Main Idea", "Sequencing"],
    concernTags: ["inferential difficulty", "vocabulary difficulty", "visual support needed", "high prompting needed"],
    summary: "High support pattern: reading comprehension performance is limited without visual support and repeated guidance.",
    supportNeedEstimate: "High Support Need",
    notes: "Responded more accurately when choices were presented with pictures and one step at a time.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "A-102",
    learnerId: "L-002",
    date: "2026-06-02",
    literalScore: 7,
    inferentialScore: 6,
    vocabularyScore: 6,
    sequencingScore: 4,
    mainIdeaScore: 5,
    followingInstructionsScore: 7,
    attentionDuringReadingScore: 6,
    promptingNeededScore: 5,
    responseMode: "Oral",
    accommodationsUsed: ["Graphic organizers", "Chunked reading tasks"],
    source: "Academic Assessment",
    totalScore: 28,
    percentage: 56,
    lowestDomains: ["Sequencing", "Main Idea"],
    concernTags: ["sequencing difficulty", "main idea difficulty"],
    summary: "Moderate support pattern: sequencing and main-idea tasks need targeted instructional scaffolds.",
    supportNeedEstimate: "Moderate Support Need",
    notes: "Stronger with explicit detail recall than with sequencing and summarization.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "A-103",
    learnerId: "L-004",
    date: "2026-06-05",
    literalScore: 8,
    inferentialScore: 4,
    vocabularyScore: 5,
    sequencingScore: 7,
    mainIdeaScore: 6,
    followingInstructionsScore: 8,
    attentionDuringReadingScore: 7,
    promptingNeededScore: 4,
    responseMode: "Oral",
    accommodationsUsed: ["Vocabulary preview", "Teacher think-aloud"],
    source: "SPED activity",
    totalScore: 30,
    percentage: 60,
    lowestDomains: ["Inferential Comprehension", "Vocabulary"],
    concernTags: ["inferential difficulty", "vocabulary difficulty"],
    summary: "Moderate support pattern: inferential comprehension remains a targeted need despite stronger classroom participation.",
    supportNeedEstimate: "Moderate Support Need",
    notes: "Sentence starters increased oral response clarity during guided discussion.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "A-104",
    learnerId: "L-006",
    date: "2026-06-06",
    literalScore: 8,
    inferentialScore: 6,
    vocabularyScore: 7,
    sequencingScore: 8,
    mainIdeaScore: 6,
    followingInstructionsScore: 8,
    attentionDuringReadingScore: 8,
    promptingNeededScore: 3,
    responseMode: "Written",
    accommodationsUsed: ["Graphic organizers", "Key-detail highlighting"],
    source: "Teacher-administered reading task",
    totalScore: 35,
    percentage: 70,
    lowestDomains: [],
    concernTags: ["main idea difficulty", "inferential difficulty"],
    summary: "Low support pattern: learner is generally independent but still benefits from guided inferential and main-idea support.",
    supportNeedEstimate: "Low Support Need",
    notes: "Maintains accuracy with guided organizer use.",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockObservations: Observation[] = [
  {
    id: "O-101",
    learnerId: "L-001",
    date: "2026-06-01",
    sessionType: "One-on-one intervention",
    behaviorIndicators: ["Attention shifts away from text without prompt", "Needs repeated instruction"],
    communicationIndicators: ["Uses picture-supported choices", "Needs modeled verbal response"],
    learningResponse: "Responded best when questions were paired with visuals and simplified wording.",
    promptingLevel: "High prompting",
    accommodationsUsed: ["Visual schedules", "Picture-supported choices"],
    strengthsObserved: ["Identified familiar vocabulary with picture cues", "Participated during guided oral response"],
    concernsObserved: ["Difficulty explaining hidden meaning", "Needed repeated redirection during reading task"],
    nlpTags: ["inferential difficulty", "vocabulary difficulty", "visual support needed", "repeated instruction needed", "high prompting needed"],
    extractedEvidence: [
      "Observation indicates repeated prompting during a reading task.",
      "Narrative suggests stronger response when visuals are present.",
    ],
    narrative: "Learner required repeated instruction during inferential questions and responded better when visual choices and modeled language were provided.",
    teacherId: "teacher-alvin",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "O-102",
    learnerId: "L-002",
    date: "2026-06-03",
    sessionType: "Classroom session",
    behaviorIndicators: ["Works steadily after modeling"],
    communicationIndicators: ["Can retell orally before writing"],
    learningResponse: "Sequencing improves when events are moved physically before discussion.",
    promptingLevel: "Moderate prompting",
    accommodationsUsed: ["Graphic organizers"],
    strengthsObserved: ["Recalls character and setting details", "Engages with manipulatives"],
    concernsObserved: ["Misses central idea without a frame", "Needs cue to order events"],
    nlpTags: ["sequencing difficulty", "main idea difficulty", "positive response to pictures"],
    extractedEvidence: [
      "Narrative mentions sequencing improvement with physical ordering tasks.",
      "Main-idea support is still needed during summary tasks.",
    ],
    narrative: "Learner can recall details but needs cueing to sequence events and identify the main idea. She responds positively to picture-supported organizers.",
    teacherId: "teacher-alvin",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "O-103",
    learnerId: "L-004",
    date: "2026-06-05",
    sessionType: "Therapy coordination",
    behaviorIndicators: ["Sustains reading task with teacher support"],
    communicationIndicators: ["Benefits from oral rehearsal", "Uses sentence starters effectively"],
    learningResponse: "Can answer guided why/how questions after think-aloud modeling.",
    promptingLevel: "Minimal prompting",
    accommodationsUsed: ["Vocabulary preview", "Teacher think-aloud"],
    strengthsObserved: ["Strong literal recall", "Improved expressive response after rehearsal"],
    concernsObserved: ["Vocabulary precision drops on unfamiliar words", "Inferential answers still need cueing"],
    nlpTags: ["inferential difficulty", "vocabulary difficulty"],
    extractedEvidence: [
      "Observation notes improved response after oral rehearsal.",
      "Inferential answers remain dependent on guided prompts.",
    ],
    narrative: "Learner used sentence starters after oral rehearsal and answered more accurately, but inferential and vocabulary demands still required guided support.",
    teacherId: "teacher-alvin",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockRecommendations: Recommendation[] = [
  {
    id: "R-101",
    learnerId: "L-001",
    date: "2026-06-02",
    assessmentId: "A-101",
    observationId: "O-101",
    classifiedSupportLevel: "High Support Need",
    targetConcern: "Inferential comprehension with high prompting needs",
    recommendedStrategies: [
      "Picture-word matching before passage reading",
      "Guided why/how questions with visual choices",
      "Least-to-most prompting routine",
    ],
    suggestedFrequency: "4 short guided sessions per week",
    materialsSupportsNeeded: ["Picture-supported question cards", "Visual schedule strip", "AAC answer choices"],
    cautionNotes: "Use one-step directions and pause for processing time before repeating prompts.",
    contributingFactors: [
      "Low inferential comprehension and vocabulary scores.",
      "High prompting needed during reading tasks.",
      "Positive response to visual supports in observation and external reports.",
    ],
    evidence: [
      "Dev Ped and ST summaries both note stronger participation with visual support.",
      "Observation shows repeated instruction was needed during inferential questions.",
    ],
    dataConsidered: [
      "Academic reading assessment summary",
      "Teacher observation notes",
      "IEP-aligned goals",
      "Authorized external report summaries",
      "Current accommodations",
    ],
    nlpDifficultyTags: ["inferential difficulty", "vocabulary difficulty", "visual support needed", "high prompting needed"],
    reasoningSteps: [
      "Assessment scores identified the lowest comprehension domains.",
      "Observation and external-report summaries confirmed high support need during language-heavy reading tasks.",
      "Intervention suggestions were matched to the learner's performance pattern, not to diagnosis alone.",
      "Recommendation remains a draft until reviewed by an expert and confirmed with the parent/guardian.",
    ],
    teacherReviewStatus: "Needs Revision",
    validationStatus: "For expert review",
    teacherNotes: "Send to center team for expert review before converting to active plan.",
    reviewedAt: "2026-06-03T10:00:00.000Z",
    reviewedBy: "Teacher Alvin",
    progressStatus: "Needs Modified Support",
    confidence: 91,
    reviewedByTeacher: false,
    requiresParentConfirmation: true,
    parentGuardianConfirmationStatus: "Pending",
    validationNotes: "Waiting for expert team review and parent conference.",
    validationRecords: [
      {
        id: "VR-101",
        recommendationId: "R-101",
        status: "For expert review",
        reviewerName: "Teacher Alvin",
        reviewerRole: "SNED Teacher",
        reviewDate: "2026-06-03",
        notes: "Draft recommendation prepared for interdisciplinary team validation.",
        requiresParentConfirmation: true,
      },
    ],
    linkedGoal: "Follow 2-step reading task instructions with visual cueing",
    editableFrequency: "4 short guided sessions per week",
    editableMaterials: ["Picture-supported question cards", "Visual schedule strip", "AAC answer choices"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "R-102",
    learnerId: "L-002",
    date: "2026-06-03",
    assessmentId: "A-102",
    observationId: "O-102",
    classifiedSupportLevel: "Moderate Support Need",
    targetConcern: "Sequencing and main-idea organization",
    recommendedStrategies: [
      "Beginning-middle-end organizer",
      "Story sequencing cards",
      "Guided summary frame",
    ],
    suggestedFrequency: "3 sessions per week during reading support block",
    materialsSupportsNeeded: ["Sequencing cards", "Story map template", "Summary sentence frame"],
    cautionNotes: "Fade prompts gradually after the learner completes event ordering correctly.",
    contributingFactors: [
      "Low sequencing and main-idea scores.",
      "Observation confirms stronger response to visual organizers and oral retell.",
    ],
    evidence: [
      "Academic assessment summary identified sequencing and summarization as primary needs.",
      "Observation showed a positive response to picture-supported organizers.",
    ],
    dataConsidered: [
      "Academic assessment summary",
      "Teacher observation notes",
      "Current IEP-aligned goals",
      "Classroom accommodations",
    ],
    nlpDifficultyTags: ["sequencing difficulty", "main idea difficulty", "positive response to pictures"],
    reasoningSteps: [
      "Assessment performance showed targeted concerns rather than broad difficulty across all domains.",
      "Observation data was used to choose organizer-based supports with lighter prompting.",
      "Condition status was treated as contextual only and did not determine the final recommendation.",
      "Draft recommendation still requires expert and parent validation before activation.",
    ],
    teacherReviewStatus: "Pending Review",
    validationStatus: "Draft recommendation",
    teacherNotes: "",
    progressStatus: "Improving",
    confidence: 84,
    reviewedByTeacher: false,
    requiresParentConfirmation: true,
    parentGuardianConfirmationStatus: "Pending",
    validationNotes: "",
    validationRecords: [],
    linkedGoal: "Sequence 4 story events using a beginning-middle-end organizer",
    editableFrequency: "3 sessions per week during reading support block",
    editableMaterials: ["Sequencing cards", "Story map template", "Summary sentence frame"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "R-103",
    learnerId: "L-004",
    date: "2026-06-06",
    assessmentId: "A-103",
    observationId: "O-103",
    classifiedSupportLevel: "Moderate Support Need",
    targetConcern: "Inferential comprehension with expressive language support",
    recommendedStrategies: [
      "Guided why/how questioning",
      "Think-aloud modeling",
      "Sentence starters for inferential answers",
    ],
    suggestedFrequency: "2 focused sessions plus classroom carryover each week",
    materialsSupportsNeeded: ["Why/how prompt cards", "Inference clue chart", "Sentence starter strip"],
    cautionNotes: "Allow oral rehearsal before asking for a complete independent response.",
    contributingFactors: [
      "Inferential comprehension remains lower than literal recall.",
      "Speech/language summary and observation both show improved performance with oral rehearsal.",
    ],
    evidence: [
      "Speech therapy summary recommends oral rehearsal and sentence starters.",
      "Observation confirms stronger verbal output after modeling.",
    ],
    dataConsidered: [
      "Academic reading assessment summary",
      "Therapy coordination observation",
      "Speech therapy summary",
      "IEP-aligned goals",
    ],
    nlpDifficultyTags: ["inferential difficulty", "vocabulary difficulty"],
    reasoningSteps: [
      "Assessment and observation were combined to isolate inferential rather than decoding needs.",
      "External report information was used only as contextual planning support.",
      "Recommendation remains support documentation and does not replace specialist judgment.",
    ],
    teacherReviewStatus: "Approved",
    validationStatus: "Parent confirmed",
    teacherNotes: "Expert review supported the draft with minor wording edits.",
    reviewedAt: "2026-06-07T09:00:00.000Z",
    reviewedBy: "Teacher Alvin",
    progressStatus: "Stable",
    confidence: 82,
    reviewedByTeacher: true,
    requiresParentConfirmation: true,
    parentGuardianConfirmationStatus: "Confirmed",
    validationNotes: "Ready to activate as an intervention plan.",
    validationRecords: [
      {
        id: "VR-103",
        recommendationId: "R-103",
        status: "Expert approved",
        reviewerName: "Ms. Reyes",
        reviewerRole: "Reading Coordinator",
        reviewDate: "2026-06-07",
        notes: "Recommendation is appropriate with sentence-starter support retained.",
        requiresParentConfirmation: true,
      },
      {
        id: "VR-104",
        recommendationId: "R-103",
        status: "Parent confirmed",
        reviewerName: "Parent/Guardian",
        reviewerRole: "Parent/Guardian",
        reviewDate: "2026-06-08",
        notes: "Parent agrees with school-based reading support plan.",
        requiresParentConfirmation: false,
      },
    ],
    linkedGoal: "Answer guided why/how questions using sentence frames",
    editableFrequency: "2 focused sessions plus classroom carryover each week",
    editableMaterials: ["Why/how prompt cards", "Inference clue chart", "Sentence starter strip"],
    createdAt: now,
    updatedAt: now,
  },
];

export const mockInterventionPlans: InterventionPlan[] = [
  {
    id: "IP-201",
    learnerId: "L-004",
    recommendationId: "R-103",
    targetSkill: "Inferential comprehension",
    strategy: "Guided why/how questioning with sentence starters",
    linkedGoal: "Answer guided why/how questions using sentence frames",
    frequency: "2 focused sessions plus classroom carryover each week",
    duration: "20 minutes per session",
    materials: ["Why/how prompt cards", "Inference clue chart", "Sentence starter strip"],
    responsiblePerson: "Reading Teacher Maria",
    startDate: "2026-06-09",
    reviewDate: "2026-06-30",
    status: "Active",
    notes: "Validated by expert review and parent confirmation.",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockProgressRecords: ProgressRecord[] = [
  {
    id: "PR-301",
    learnerId: "L-004",
    interventionPlanId: "IP-201",
    progressDate: "2026-06-13",
    targetSkill: "Inferential comprehension",
    activityMaterialUsed: "Short story with guided why/how question cards",
    currentScore: 7.2,
    promptingLevel: "Minimal prompting",
    taskCompletion: "Completed",
    attentionEngagement: "Occasional redirection",
    responseMode: "Oral",
    totalItems: 5,
    correctResponses: 3,
    comprehensionAccuracy: "3/5 (60%)",
    computedAccuracy: 60,
    computedProgressScore: 7.2,
    scoreChangeFromPrevious: null,
    computedProgressStatus: "Improving",
    systemSuggestedAction: "Continue",
    systemSuggestionReason: "The computed score is at or above the support threshold and does not show a concerning decline.",
    finalAction: "Continue",
    finalActionReason: "Continue the validated plan and monitor whether oral sentence frames improve independent why/how responses.",
    teacherTherapistNotes: "Sentence starters and oral rehearsal helped organize responses.",
    parentFeedback: "Parent reported similar success when discussing a short story at home.",
    recommendedAction: "Continue",
    reason: "Continue the validated plan and monitor whether oral sentence frames improve independent why/how responses.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "PR-302",
    learnerId: "L-004",
    interventionPlanId: "IP-201",
    progressDate: "2026-06-17",
    targetSkill: "Inferential comprehension",
    activityMaterialUsed: "Picture-supported passage with why/how answer choices",
    currentScore: 8.2,
    promptingLevel: "Minimal prompting",
    taskCompletion: "Completed",
    attentionEngagement: "Occasional redirection",
    responseMode: "Picture choices",
    totalItems: 5,
    correctResponses: 4,
    comprehensionAccuracy: "4/5 (80%)",
    computedAccuracy: 80,
    computedProgressScore: 8.2,
    scoreChangeFromPrevious: 1,
    computedProgressStatus: "Improving",
    systemSuggestedAction: "Continue",
    systemSuggestionReason: "The score improved by at least one point and the learner required only independent or minimal prompting.",
    finalAction: "Continue",
    finalActionReason: "Continue for the next two sessions while gradually reducing picture choices during inferential questions.",
    teacherTherapistNotes: "Learner answered why/how questions more accurately after picture clues were previewed.",
    parentFeedback: "Parent observed better participation when story questions used picture choices.",
    recommendedAction: "Continue",
    reason: "Continue for the next two sessions while gradually reducing picture choices during inferential questions.",
    createdAt: now,
    updatedAt: now,
  },
];
